#pragma once

#include "NativeGameplayTags.h"

namespace MysticaGameplayTags {
MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);

MYSTICA_API
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);
} // namespace MysticaGameplayTags
